language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
script: mvn clean install
dist: trusty

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: bash .travis/release.sh
  on:
    tags: true
    branch: release